version: 3.10

services:
  app:
    build:
      context: .
      dockerfile: ./app/Dockerfile
    depends_on:
      - db
      - rabbit-mq
    ports:
      - "5000:5000"
    env_file:
      - ./.env
    environment:
      - PYTHONPATH=/app
      - FLASK_ENV=development
    networks:
      - backend

  nginx:
    build: ./nginx/
    ports:
      - "80:80"
      - "443:443"
    networks:
      - backend

  networks:
    - backend

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    env_file:
      - ./.env
