version: '3.10'

services:
  app:
    build:
      context: .
      dockerfile: ./app/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    env_file:
      - ./.env
    environment:
      - PYTHONPATH=/app
      - FLASK_ENV=development
    volumes:
      - ./app:/app
    command: bash -c "alembic revision --autogenerate; alembic upgrade head && uvicorn api:app --host 0.0.0.0 --port 8080 --reload"
    #command: bash -c "alembic downgrade base; alembic upgrade head"
    networks:
      - backend

  nginx:
    build: ./nginx/
    ports:
      - "80:80"
      - "443:443"
    networks:
      - backend

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    env_file:
      - ./.env
    networks:
      - backend

  db:
    image: postgres:latest
    user: postgres
    ports:
      - "5432:5432"
    env_file:
      - ./.env
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_NAME: postgres
    networks:
      - backend
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

networks:
  backend:
    driver: bridge