version: '3.10'

services:
  app:
    build:
      context: .
      dockerfile: ./app/Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - ./.env
    environment:
      - PYTHONPATH=/app
      - FLASK_ENV=development
    volumes:
      - ./app:/app
    networks:
      - backend

  nginx:
    build: ./nginx/
    ports:
      - "80:80"
      - "443:443"
    networks:
      - backend

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    env_file:
      - ./.env
    networks:
      - backend

networks:
  backend:
    driver: bridge