version: '3.10'

services:
  app:
    build:
      context: .
      dockerfile: ./app/Dockerfile
    ports:
      - "8083:8083"
    depends_on:
      - db
    env_file:
      - ./.env
    environment:
      - PYTHONPATH=/app
      - FLASK_ENV=development
    volumes:
      - ./app:/app
    networks:
      - backend

  nginx:
    build: ./nginx/
    ports:
      - "80:80"
      - "443:443"
    networks:
      - backend

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    env_file:
      - ./.env
    networks:
      - backend

  db:
    image: postgres:latest
    user: postgres
    ports:
      - "5432:5432"
    env_file:
      - ./.env
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    networks:
      - backend
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

networks:
  backend:
    driver: bridge