"""Добавить авторов

Revision ID: 174b4692f82f
Revises: d37e7f8641d4
Create Date: 2025-03-21 18:22:44.999267

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '174b4692f82f'
down_revision: Union[str, None] = 'd37e7f8641d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('authors', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'authors')
    # ### end Alembic commands ###
