"""Описание изменений

Revision ID: 1b1b83dd4abb
Revises: a47c6f0cc840
Create Date: 2025-02-19 21:03:01.653942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b1b83dd4abb'
down_revision: Union[str, None] = 'a47c6f0cc840'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('method_check', sa.JSON(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'method_check')
    # ### end Alembic commands ###
