"""Init

Revision ID: 25c34e98d7fe
Revises: ee08a1b73baa
Create Date: 2024-12-31 13:55:19.801375

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25c34e98d7fe'
down_revision: Union[str, None] = 'ee08a1b73baa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('articles_doi_key', 'articles', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('articles_doi_key', 'articles', ['doi'])
    # ### end Alembic commands ###
