"""Initial

Revision ID: a47c6f0cc840
Revises: 
Create Date: 2025-02-02 14:35:49.477130

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a47c6f0cc840'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('abstract', sa.Text(), nullable=True),
    sa.Column('keywords', sa.JSON(), nullable=True),
    sa.Column('introduction', sa.Text(), nullable=True),
    sa.Column('methods', sa.Text(), nullable=True),
    sa.Column('results', sa.Text(), nullable=True),
    sa.Column('discussion', sa.Text(), nullable=True),
    sa.Column('conclusion', sa.Text(), nullable=True),
    sa.Column('references', sa.Text(), nullable=True),
    sa.Column('article_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('experiments')
    op.alter_column('articles', 'full_text',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_constraint('articles_link_key', 'articles', type_='unique')
    op.drop_column('articles', 'authors')
    op.drop_column('articles', 'snippet')
    op.drop_column('articles', 'link')
    op.drop_column('articles', 'abstract')
    op.drop_column('articles', 'source')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('source', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('articles', sa.Column('abstract', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('articles', sa.Column('link', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('articles', sa.Column('snippet', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('articles', sa.Column('authors', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_unique_constraint('articles_link_key', 'articles', ['link'])
    op.alter_column('articles', 'full_text',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.create_table('experiments',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('objects', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('methods', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('parameters', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('results', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('article_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], name='experiments_article_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='experiments_pkey'),
    sa.UniqueConstraint('objects', name='experiments_objects_key')
    )
    op.drop_table('sections')
    # ### end Alembic commands ###
